spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers:  192.168.99.101:9092
      bindings:
        message-in:
          destination: testq.in
          contentType: application/json
        message-out:
          destination: testq.out
          contentType: application/json